name: Publish TypeScript SDK

on:
  workflow_dispatch:
  push:
    tags: ["sdk-js-v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false
      - run: npm install && npm test
        working-directory: typescript
      - run: npm publish --provenance --access public
        working-directory: typescript
